name: Deploy Create Short URL Lambda
on:
  push:
    branches:
      - main
    paths:
      - apps/create-short-url/**/*
      - .github/workflows/deploy-create-short-url-lambda.yml

defaults:
  run:
    working-directory: apps/create-short-url/

jobs:
  terraform:
    name: 'Deploy Create Short URL Lambda'
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Zip the Python script
      - name: Zip the script
        run: zip -r ../create_short_url.zip create_short_url.py

      # Update Lambda function code
      - name: Update Lambda code
        run: aws lambda update-function-code --function-name=create-short-url --zip-file=fileb://../create_short_url.zip